spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/highestway?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1207
    driver-class-name: com.mysql.cj.jdbc.Driver

  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
#        show_sql: true
        format_sql: true
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    user: root
    password: 1207

logging.level:
  org.hibernate.SQL: debug